

/*
JEITO ERRADO DE FAZER: Deixei para documentar meu erro
-- Asthma Status
DROP TABLE IF EXISTS dbo.AsthmaStatus;

CREATE TABLE AsthmaStatus (
ID INT NOT NULL PRIMARY KEY,
ASTHMS1 SMALLINT,
LTASTH1 SMALLINT,
CASTHM1 SMALLINT
);

-- Demographics
DROP TABLE IF EXISTS dbo.Demographics;

CREATE TABLE Demographics (
ID INT NOT NULL PRIMARY KEY,
SEXVAR SMALLINT NOT NULL,
INCOME3 SMALLINT,
AGEG5YR SMALLINT,
WTKG3 DECIMAL(7,2),
HTM4 DECIMAL(5,2),
BMI5 DECIMAL(6,2),
BMI5CAT SMALLINT,
RFBMI5 SMALLINT
);

-- Exercise Status
DROP TABLE IF EXISTS dbo.ExerciseStatus;

CREATE TABLE ExerciseStatus (
ID INT NOT NULL PRIMARY KEY,
EXERANY2 SMALLINT,
TOTINDA SMALLINT
);


--Health Status

DROP TABLE IF EXISTS dbo.HealthStatus;

CREATE TABLE HealthStatus(
ID INT NOT NULL PRIMARY KEY,
GENHLTH SMALLINT,
PHYS14D SMALLINT,
PHYSHLTH SMALLINT,
DIFFWALK SMALLINT,
DIFFALON SMALLINT,
RFHLTH SMALLINT

);


--Tobbaco use

DROP TABLE IF EXISTS dbo.TobbacoUse;

CREATE TABLE TobbacoUse (
ID INT NOT NULL PRIMARY KEY,
 SMOKE100 SMALLINT,
 SMOKDAY2 SMALLINT,
USENOW3 SMALLINT,
ECIGNOW1 SMALLINT,
SMOKER3 SMALLINT,
RFSMOK3 SMALLINT,
CURECI1 SMALLINT,
LCSFIRST SMALLINT,
 LCSLAST SMALLINT,
 LCSNUMCG SMALLINT,
LASTSMK2 SMALLINT,
 STOPSMK2 SMALLINT
);


--Alcohol Consumption
DROP TABLE IF EXISTS dbo.AlcoholConsu;
CREATE TABLE AlcoholConsu (
ID INT NOT NULL PRIMARY KEY,
ALCDAY5 SMALLINT,
AVEDRNK3 SMALLINT,
DRNKANY5 SMALLINT,
DROCDY3 SMALLINT,
RFBING5 SMALLINT,
DRNKWK1 INT,
RFDRHV7 SMALLINT
);


--Drugs and Marijuana Use
DROP TABLE IF EXISTS dbo.DrugsUse;

CREATE TABLE DrugsUse (
ID INT NOT NULL PRIMARY KEY,
ACEDRUGS SMALLINT,
MARIJAN1 SMALLINT,
RSNMRJN2 SMALLINT
);

--Immunization
DROP TABLE IF EXISTS dbo.Immuni

CREATE TABLE Immuni(
ID INT NOT NULL PRIMARY KEY,
FLUSHOT7 SMALLINT,
PNEUVAC4 SMALLINT,
FLSHOT7  SMALLINT,
PNEUMO3 SMALLINT
);



--Urban Rural
DROP TABLE IF EXISTS dbo.UrbanRural

CREATE TABLE UrbanRural(
ID INT NOT NULL PRIMARY KEY,
METSTAT SMALLINT,
URBSTAT SMALLINT
);

*/